services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src

  js-express-server:
    build:
      context: ./js-express-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./js-express-server/src:/app/src
      - ./js-express-server/package.json:/app/package.json
      - ./js-express-server/yarn.lock:/app/yarn.lock
